# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/liren/code/projects/c/game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/liren/code/projects/c/game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/liren/code/projects/c/game/CMakeFiles /Users/liren/code/projects/c/game//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/liren/code/projects/c/game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Game

# Build rule for target.
Game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Game
.PHONY : Game

# fast build rule for target.
Game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/build
.PHONY : Game/fast

#=============================================================================
# Target rules for targets named SDL3-shared

# Build rule for target.
SDL3-shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3-shared
.PHONY : SDL3-shared

# fast build rule for target.
SDL3-shared/fast:
	$(MAKE) $(MAKESILENT) -f vendored/SDL/CMakeFiles/SDL3-shared.dir/build.make vendored/SDL/CMakeFiles/SDL3-shared.dir/build
.PHONY : SDL3-shared/fast

#=============================================================================
# Target rules for targets named SDL3_test

# Build rule for target.
SDL3_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3_test
.PHONY : SDL3_test

# fast build rule for target.
SDL3_test/fast:
	$(MAKE) $(MAKESILENT) -f vendored/SDL/CMakeFiles/SDL3_test.dir/build.make vendored/SDL/CMakeFiles/SDL3_test.dir/build
.PHONY : SDL3_test/fast

#=============================================================================
# Target rules for targets named SDL_uclibc

# Build rule for target.
SDL_uclibc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL_uclibc
.PHONY : SDL_uclibc

# fast build rule for target.
SDL_uclibc/fast:
	$(MAKE) $(MAKESILENT) -f vendored/SDL/CMakeFiles/SDL_uclibc.dir/build.make vendored/SDL/CMakeFiles/SDL_uclibc.dir/build
.PHONY : SDL_uclibc/fast

#=============================================================================
# Target rules for targets named SDL3_image-shared

# Build rule for target.
SDL3_image-shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3_image-shared
.PHONY : SDL3_image-shared

# fast build rule for target.
SDL3_image-shared/fast:
	$(MAKE) $(MAKESILENT) -f vendored/SDL_image/CMakeFiles/SDL3_image-shared.dir/build.make vendored/SDL_image/CMakeFiles/SDL3_image-shared.dir/build
.PHONY : SDL3_image-shared/fast

#=============================================================================
# Target rules for targets named SDL3_ttf-shared

# Build rule for target.
SDL3_ttf-shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3_ttf-shared
.PHONY : SDL3_ttf-shared

# fast build rule for target.
SDL3_ttf-shared/fast:
	$(MAKE) $(MAKESILENT) -f vendored/SDL_ttf/CMakeFiles/SDL3_ttf-shared.dir/build.make vendored/SDL_ttf/CMakeFiles/SDL3_ttf-shared.dir/build
.PHONY : SDL3_ttf-shared/fast

controllers/enemy.o: controllers/enemy.c.o
.PHONY : controllers/enemy.o

# target to build an object file
controllers/enemy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/enemy.c.o
.PHONY : controllers/enemy.c.o

controllers/enemy.i: controllers/enemy.c.i
.PHONY : controllers/enemy.i

# target to preprocess a source file
controllers/enemy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/enemy.c.i
.PHONY : controllers/enemy.c.i

controllers/enemy.s: controllers/enemy.c.s
.PHONY : controllers/enemy.s

# target to generate assembly for a file
controllers/enemy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/enemy.c.s
.PHONY : controllers/enemy.c.s

controllers/game.o: controllers/game.c.o
.PHONY : controllers/game.o

# target to build an object file
controllers/game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/game.c.o
.PHONY : controllers/game.c.o

controllers/game.i: controllers/game.c.i
.PHONY : controllers/game.i

# target to preprocess a source file
controllers/game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/game.c.i
.PHONY : controllers/game.c.i

controllers/game.s: controllers/game.c.s
.PHONY : controllers/game.s

# target to generate assembly for a file
controllers/game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/game.c.s
.PHONY : controllers/game.c.s

controllers/map.o: controllers/map.c.o
.PHONY : controllers/map.o

# target to build an object file
controllers/map.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/map.c.o
.PHONY : controllers/map.c.o

controllers/map.i: controllers/map.c.i
.PHONY : controllers/map.i

# target to preprocess a source file
controllers/map.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/map.c.i
.PHONY : controllers/map.c.i

controllers/map.s: controllers/map.c.s
.PHONY : controllers/map.s

# target to generate assembly for a file
controllers/map.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/map.c.s
.PHONY : controllers/map.c.s

controllers/player.o: controllers/player.c.o
.PHONY : controllers/player.o

# target to build an object file
controllers/player.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/player.c.o
.PHONY : controllers/player.c.o

controllers/player.i: controllers/player.c.i
.PHONY : controllers/player.i

# target to preprocess a source file
controllers/player.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/player.c.i
.PHONY : controllers/player.c.i

controllers/player.s: controllers/player.c.s
.PHONY : controllers/player.s

# target to generate assembly for a file
controllers/player.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/player.c.s
.PHONY : controllers/player.c.s

controllers/sdl.o: controllers/sdl.c.o
.PHONY : controllers/sdl.o

# target to build an object file
controllers/sdl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/sdl.c.o
.PHONY : controllers/sdl.c.o

controllers/sdl.i: controllers/sdl.c.i
.PHONY : controllers/sdl.i

# target to preprocess a source file
controllers/sdl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/sdl.c.i
.PHONY : controllers/sdl.c.i

controllers/sdl.s: controllers/sdl.c.s
.PHONY : controllers/sdl.s

# target to generate assembly for a file
controllers/sdl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/sdl.c.s
.PHONY : controllers/sdl.c.s

controllers/ui.o: controllers/ui.c.o
.PHONY : controllers/ui.o

# target to build an object file
controllers/ui.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/ui.c.o
.PHONY : controllers/ui.c.o

controllers/ui.i: controllers/ui.c.i
.PHONY : controllers/ui.i

# target to preprocess a source file
controllers/ui.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/ui.c.i
.PHONY : controllers/ui.c.i

controllers/ui.s: controllers/ui.c.s
.PHONY : controllers/ui.s

# target to generate assembly for a file
controllers/ui.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/controllers/ui.c.s
.PHONY : controllers/ui.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Game"
	@echo "... SDL3-shared"
	@echo "... SDL3_image-shared"
	@echo "... SDL3_test"
	@echo "... SDL3_ttf-shared"
	@echo "... SDL_uclibc"
	@echo "... controllers/enemy.o"
	@echo "... controllers/enemy.i"
	@echo "... controllers/enemy.s"
	@echo "... controllers/game.o"
	@echo "... controllers/game.i"
	@echo "... controllers/game.s"
	@echo "... controllers/map.o"
	@echo "... controllers/map.i"
	@echo "... controllers/map.s"
	@echo "... controllers/player.o"
	@echo "... controllers/player.i"
	@echo "... controllers/player.s"
	@echo "... controllers/sdl.o"
	@echo "... controllers/sdl.i"
	@echo "... controllers/sdl.s"
	@echo "... controllers/ui.o"
	@echo "... controllers/ui.i"
	@echo "... controllers/ui.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

